# Generated by Django 3.2.8 on 2021-11-07 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BooleanField(default=True, verbose_name='name')),
                ('address', models.BooleanField(default=True, verbose_name='address')),
                ('department', models.BooleanField(default=True, verbose_name='department')),
                ('link', models.BooleanField(default=True, verbose_name='link')),
                ('monday', models.BooleanField(default=True, verbose_name='monday')),
                ('tuesday', models.BooleanField(default=True, verbose_name='tuesday')),
                ('wednesday', models.BooleanField(default=True, verbose_name='wednesday')),
                ('thursday', models.BooleanField(default=True, verbose_name='thursday')),
                ('friday', models.BooleanField(default=True, verbose_name='friday')),
                ('saturday', models.BooleanField(default=True, verbose_name='saturday')),
                ('sunday', models.BooleanField(default=True, verbose_name='sunday')),
                ('holiday', models.BooleanField(default=True, verbose_name='holiday')),
                ('page', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='page')),
            ],
        ),
    ]
