# Generated by Django 3.2.8 on 2021-10-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_scraping', '0002_auto_20211030_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='link',
            field=models.BooleanField(default=True, verbose_name='department'),
        ),
    ]
