# Generated by Django 3.2.8 on 2021-10-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_scraping', '0003_condition_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='link',
            field=models.BooleanField(default=True, verbose_name='link'),
        ),
    ]
